# Generated by Django 4.2.5 on 2023-09-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbidsapi', '0002_contractor_primary_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
