# Generated by Django 4.2.5 on 2023-09-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbidsapi', '0003_bid_accepted_bid_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='blueprint',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='complete',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='open',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='square_footage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
