# Generated by Django 4.2.5 on 2023-09-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbidsapi', '0004_job_blueprint_job_complete_job_open_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='field',
            new_name='fields',
        ),
    ]
