# Generated by Django 4.2.5 on 2023-09-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbidsapi', '0005_rename_field_job_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='blueprint',
            field=models.ImageField(blank=True, null=True, upload_to='blueprints/'),
        ),
    ]
