# Generated by Django 4.2.5 on 2023-09-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickbidsapi', '0006_bid_request_alter_job_blueprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='request',
            new_name='is_request',
        ),
    ]
